#
# Add Poco libraries to project
#
include(FetchContent)

FetchContent_Declare(
	poco
	GIT_REPOSITORY https://github.com/pocoproject/poco.git
	GIT_TAG poco-1.12.4-release
)

set(ENABLE_FOUNDATION ON CACHE BOOL "" FORCE)

set(ENABLE_ENCODINGS OFF CACHE BOOL "" FORCE)
set(ENABLE_ENCODINGS_COMPILER OFF CACHE BOOL "" FORCE)
set(ENABLE_XML OFF CACHE BOOL "" FORCE)
set(ENABLE_JSON OFF CACHE BOOL "" FORCE)

set(ENABLE_DATA OFF CACHE BOOL "" FORCE)
set(ENABLE_DATA_MYSQL OFF CACHE BOOL "" FORCE)
set(ENABLE_DATA_POSTGRESQL OFF CACHE BOOL "" FORCE)
set(ENABLE_DATA_ODBC OFF CACHE BOOL "" FORCE)
set(ENABLE_MONGODB OFF CACHE BOOL "" FORCE)
set(ENABLE_DATA_SQLITE OFF CACHE BOOL "" FORCE)
set(ENABLE_REDIS OFF CACHE BOOL "" FORCE)

set(ENABLE_PROMETHEUS OFF CACHE BOOL "" FORCE)
set(ENABLE_PDF OFF CACHE BOOL "" FORCE)
set(ENABLE_UTIL ON CACHE BOOL "" FORCE)
set(ENABLE_NET OFF CACHE BOOL "" FORCE)

set(ENABLE_NETSSL OFF CACHE BOOL "" FORCE)
set(ENABLE_CRYPTO OFF CACHE BOOL "" FORCE)
set(ENABLE_JWT OFF CACHE BOOL "" FORCE)

set(ENABLE_SEVENZIP OFF CACHE BOOL "" FORCE)
set(ENABLE_ZIP OFF CACHE BOOL "" FORCE)

set(ENABLE_CPPPARSER OFF CACHE BOOL "" FORCE)
set(ENABLE_POCODOC OFF CACHE BOOL "" FORCE)
set(ENABLE_PAGECOMPILER OFF CACHE BOOL "" FORCE)
set(ENABLE_PAGECOMPILER_FILE2PAGE OFF CACHE BOOL "" FORCE)

set(ENABLE_ACTIVERECORD OFF CACHE BOOL "" FORCE)
set(ENABLE_ACTIVERECORD_COMPILER OFF CACHE BOOL "" FORCE)

FetchContent_MakeAvailable(poco)

